config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root  'home#index'

  resources :people
  resources :events do
    resources :booths do
      get '/new',             to: 'booths#atnuser'
      post '/create',         to: 'booths#createatnuser'
    end
    resources :reserves, only: [:new, :create, :edit, :update]
  end
  #QR
  get   '/qr/:qr',            to: 'reserves#qr'

  # mobile
  post  'auth_user',          to: 'mobile_auth#authenticate_user'
  get   '/mobile/home',       to: 'mobile_home#index'
  get   '/mobile/stats',      to: 'mobile_home#stats'
  post  '/mobile/ticket',     to: 'mobile_home#ticket'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/booth.rb
class Booth < ApplicationRecord
  belongs_to :event
  has_many :resbooths
end

app/controllers/booths_controller.rb
class BoothsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_booth, only: [:show, :edit, :update, :destroy]

  # GET /booths
  # GET /booths.json
  def index
    @booths = Booth.all
    @event  = Event.find(params[:event_id])
    redirect_to event_path
  end

  # GET /booths/1
  # GET /booths/1.json
  def show
    @booth  = Booth.find(params[:id])
    @event  = @booth.event
    @vistors = Resbooth.where(booth_id: params[:id]).sort.reverse.first(20)
  end

  # GET /booths/new
  def new
    @booth = Booth.new
    @event = Event.find(params[:event_id])
  end

  # GET /booths/1/edit
  def edit
    @event  = Event.find(params[:event_id])
    @booth  = Booth.find(params[:id])
  end

  # POST /booths
  # POST /booths.json
  def create
    @booth = Booth.new(booth_params)

    respond_to do |format|
      if @booth.save
        format.html { redirect_to event_path(params[:event_id]), notice: 'Booth was successfully created.' }
        format.json { render :show, status: :created, location: @booth }
      else
        format.html { render :new }
        format.json { render json: @booth.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /booths/1
  # PATCH/PUT /booths/1.json
  def update
    respond_to do |format|
      if @booth.update(booth_params)
        format.html { redirect_to event_booth_path(@booth), notice: 'Booth was successfully updated.' }
        format.json { render :show, status: :ok, location: @booth }
      else
        format.html { render :edit }
        format.json { render json: @booth.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /booths/1
  # DELETE /booths/1.json
  def destroy
    @booth.destroy
    respond_to do |format|
      format.html { redirect_to event_booths_url, notice: 'Booth was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def atnuser
    @people   = Reserve.where(event_id: params[:event_id], ticket: true).map { |user| Person.find(user.person_id) }
    @all      = Resbooth.where(booth_id: params[:booth_id])
    @resbooth = Resbooth.new
  end

  def createatnuser
    @resbooth = Resbooth.new(booth_id: params[:booth_id], person_id: params[:resbooth][:person])
    puts params[:resbooth][:person]
    # byebug
    puts @resbooth
    if @resbooth.save
      redirect_to event_booth_new_path
    else
      flash[:notice] = 'it broke'
      redirect_to event_booth_new_path
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booth
      @booth = Booth.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def booth_params
      params.require(:booth).permit(:name, :start, :end, :sponser).merge(event_id: params[:event_id])
    end
    # def resbooth_params
    #   params.require(:resbooth).merge(booths_id: params['booth_id'], people_id: params['person'])
    # end
end

app/helpers/booths_helper.rb
module BoothsHelper
end

app/views/booths/_form.html.erb
<%= form_for([event, booth]) do |f| %>
  <% if booth.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(booth.errors.count, "error") %> prohibited this booth from being saved:</h2>

      <ul>
      <% booth.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :start %>
    <%= f.date_select :start %>
  </div>

  <div class="field">
    <%= f.label :end %>
    <%= f.date_select :end %>
  </div>

  <div class="field">
    <%= f.label :sponser %>
    <%= f.text_field :sponser %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/booths/atnuser.html.erb
<%= form_for(@resbooth, url: event_booth_create_path) do |f| %>
  <%= f.label :person_id %>
  <%= f.select("person", @people.collect {|p| [ p.name, p.id ] }, {include_blank: 'None'}) %><br/>
  <%= f.submit 'attend User', class: 'btn btn-primary' %>
<% end %>

<h1> People</h1>
<% @all.each do |person| %>
<%= person.person.name %> - Attended at: <%= person.created_at.strftime("%d-%m-%Y - %I:%M:%S %p") %></br>
<% end %>

app/views/booths/edit.html.erb
<h1>Editing Booth</h1>

<%= render 'form', event: @event, booth: @booth %>

<%= link_to 'Show', event_booth_path(@event,@booth) %> |
<%= link_to 'Back', event_path %>

app/views/booths/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Booths</h1>

<table>
  <thead>
    <tr>
      <th>Event</th>
      <th>Name</th>
      <th>Start</th>
      <th>End</th>
      <th>Sponser</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @booths.each do |booth| %>
      <tr>
        <td><%= booth.event.name %></td>
        <td><%= booth.name %></td>
        <td><%= booth.start %></td>
        <td><%= booth.end %></td>
        <td><%= booth.sponser %></td>
        <td><%= link_to 'Show', event_booth_path(booth.event.id, booth) %></td>
        <td><%= link_to 'Edit', edit_event_booth_path(booth.event.id,booth) %></td>
        <td><%= link_to 'Destroy', event_booths_path, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Booth', new_event_booth_path %>

app/views/booths/new.html.erb
<h1>New Booth</h1>

<%= render 'form', event: @event, booth: @booth %>

<%= link_to 'Back', event_path(@event) %>

app/views/booths/show.html.erb
<p id="notice"><%= notice %></p>
<h1> Booth Information</h1>

<p>
  <strong>Event:</strong>
  <%= @booth.event.name %>
</p>

<p>
  <strong>Name:</strong>
  <%= @booth.name %>
</p>

<p>
  <strong>Start:</strong>
  <%= @booth.start %>
</p>

<p>
  <strong>End:</strong>
  <%= @booth.end %>
</p>

<p>
  <strong>Sponser:</strong>
  <%= @booth.sponser %>
</p>

<%= link_to 'Edit', edit_event_booth_path(@booth) %> |
<%= link_to 'Back', event_path %>

  <h1>Visitors</h1>
  <%= link_to "Attend Booth", event_booth_new_path(@booth.event_id, @booth.id), class: 'btn btn-primary'%>
  </br>
  <% @vistors.each do |person| %>
  <%= person.person.name %> -  <%= person.created_at.strftime("%d-%m-%Y - %I:%M:%S %p") %></br>
  <% end %>