config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root  'home#index'

  resources :people
  resources :events do
    resources :booths do
      get '/new',             to: 'booths#atnuser'
      post '/create',         to: 'booths#createatnuser'
    end
    resources :reserves, only: [:new, :create, :edit, :update]
  end
  #QR
  get   '/qr/:qr',            to: 'reserves#qr'

  # mobile
  post  'auth_user',          to: 'mobile_auth#authenticate_user'
  get   '/mobile/home',       to: 'mobile_home#index'
  get   '/mobile/stats',      to: 'mobile_home#stats'
  post  '/mobile/ticket',     to: 'mobile_home#ticket'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/person.rb
class Person < ApplicationRecord
  validates :name,      presence: true, length: { minimum: 2 }
  validates :email,     presence: true
  validates :name,      presence: true
  validates :number,    presence: true,
                        numericality: true,
                        length: { minimum: 10, maximum: 15 }
  has_many  :reserve
  has_many  :resbooths
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :authenticate_user!

  def index
    @people = Person.all
    @person = Person.new
  end

  def show
    @person = Person.find(params[:id])
  end

  def create
    @person = Person.new(person_params)
    if @person.save
      flash[:notice] = "Creation successfully created"
      redirect_to people_path
    else
      flash[:alert] = "Failed to Create"
      redirect_to people_path
    end
  end

  def destroy
    @person = Person.find(params[:id])
    Reserve.destroy_all(person_id: params[:id])
    Resbooth.destroy_all(person_id: params[:id])
    if @person.destroy
      redirect_to people_path
    else
      render :show
    end
  end

  private
  def person_params
    params.require(:person).permit(:name, :email, :number)
  end

end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/index.html.erb
<section class='home-add'>
  <%= form_for @person do |f| %>
  <div class="form-group row">
       <%= f.label :name, class: 'col-sm-2 col-form-label'%>
       <div class="col-sm-10">
         <%= f.text_field :name , class: "form-control", placeholder: 'John Doe'%>
       </div>
     </div>
  <div class="form-group row">
       <%= f.label :email, class: 'col-sm-2 col-form-label'%>
       <div class="col-sm-10">
         <%= f.email_field :email , class: "form-control", placeholder: '@hotmail.com'%>
       </div>
     </div>
  <div class="form-group row">
       <%= f.label :number, class: 'col-sm-2 col-form-label'%>
       <div class="col-sm-10">
         <%= f.telephone_field :number , class: "form-control", placeholder: '1-800-222-2222'%>
       </div>
     </div>

     <div class="form-group row">
       <div class="offset-sm-2 col-sm-10">
         <%= f.submit "Create Person", class:'btn btn-primary'%>
       </div>
     </div>
  <% end %>
</section>
<section class='home-list'>
  <table class="table">
  <thead class="thead-inverse">
    <tr>
      <th>#</th>
      <th>Full Name</th>
      <th>Email</th>
      <th>Number</th>
    </tr>
  </thead>
  <tbody>
      <% @people.each do |person| %>
    <tr>
      <th scope="row"><%= person.id %></th>
      <td><%= link_to "#{person.name}", person_path(person) %></td>
      <td><%= person.email %></td>
      <td><%= person.number %></td>
    </tr>
      <% end %>
  </tbody>
</table>
</section>

app/views/people/show.html.erb
<h1><%= @person.name %></h1>
<%= link_to 'Delete Person', person_path, method: :delete, class: 'btn btn-danger' %>