config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root  'home#index'

  resources :people
  resources :events do
    resources :booths do
      get '/new',             to: 'booths#atnuser'
      post '/create',         to: 'booths#createatnuser'
    end
    resources :reserves, only: [:new, :create, :edit, :update]
  end
  #QR
  get   '/qr/:qr',            to: 'reserves#qr'

  # mobile
  post  'auth_user',          to: 'mobile_auth#authenticate_user'
  get   '/mobile/home',       to: 'mobile_home#index'
  get   '/mobile/stats',      to: 'mobile_home#stats'
  post  '/mobile/ticket',     to: 'mobile_home#ticket'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
    @people =  Person.all
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/all.html.erb
<section class='home-add'>
  <%= form_for @person do |f| %>
  <div class="form-group row">
       <%= f.label :name, class: 'col-sm-2 col-form-label'%>
       <div class="col-sm-10">
         <%= f.text_field :name , class: "form-control", placeholder: 'John Doe'%>
       </div>
     </div>
  <div class="form-group row">
       <%= f.label :email, class: 'col-sm-2 col-form-label'%>
       <div class="col-sm-10">
         <%= f.email_field :email , class: "form-control", placeholder: '@hotmail.com'%>
       </div>
     </div>
  <div class="form-group row">
       <%= f.label :number, class: 'col-sm-2 col-form-label'%>
       <div class="col-sm-10">
         <%= f.telephone_field :number , class: "form-control", placeholder: '1-800-222-2222'%>
       </div>
     </div>

     <div class="form-group row">
       <div class="offset-sm-2 col-sm-10">
         <%= f.submit "Create Person", class:'btn btn-primary'%>
       </div>
     </div>

  <% end %>
</section>
<section class='home-list'>

  <table class="table">
  <thead class="thead-inverse">
    <tr>
      <th>#</th>
      <th>Full Name</th>
      <th>Email</th>
      <th>Number</th>
    </tr>
  </thead>
  <tbody>
      <% @people.each do |person| %>
    <tr>
      <th scope="row"><%= person.id %></th>
      <td><%= person.name %></td>
      <td><%= person.email %></td>
      <td><%= person.number %></td>
    </tr>
      <% end %>
  </tbody>
</table>


</section>

app/views/home/index.html.erb
<h1> Welcome <%= current_user.email %></h1>
  <div class='row'>
    <div class='col-6'>
      <div class='card'>
        <div class="card-block carddb">
        <h4 class='card-title'>Total Database</h4>
        <%= link_to 'Mange People', people_path, class: 'btn btn-primary'%>
        <br>
        <strong>People:</strong> <%= @people.length %>
        </div>
      </div>
    </div>
    <div class='col-6'>
      <div class='card'>
        <div class="card-block carddb">
          <h4 class='card-title'>Tracking</h4>
          <strong>Person added</strong>
            <%= line_chart Person.group_by_day(:created_at).count %>

          <strong>People attend</strong>

      </div>
      </div>
    </div>
  </div>
  <section class='home-information'>
    <h4>Real Time Events</h4>
    <small>Last 20 events</small><br/>
    <% Last.last.each do |event| %>
    <%= event[0] %> <span class='pull-right'><%= event[1]%></span></br>
    <% end %>
  </section>