config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root  'home#index'

  resources :people
  resources :events do
    resources :booths do
      get '/new',             to: 'booths#atnuser'
      post '/create',         to: 'booths#createatnuser'
    end
    resources :reserves, only: [:new, :create, :edit, :update]
  end
  #QR
  get   '/qr/:qr',            to: 'reserves#qr'

  # mobile
  post  'auth_user',          to: 'mobile_auth#authenticate_user'
  get   '/mobile/home',       to: 'mobile_home#index'
  get   '/mobile/stats',      to: 'mobile_home#stats'
  post  '/mobile/ticket',     to: 'mobile_home#ticket'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
  validates :name,      presence: true
  validates :start,     presence: true
  validates :end,       presence: true
  validates :contact,   presence: true
  validates :location,  presence: true
  has_many  :booths
  has_many  :reserve
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!
  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def show
    @event   = Event.find(params[:id])
    @booths  = Booth.where(event_id: params[:id])
    @reserve = Reserve.where(event_id: params[:id])
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to events_path
    else
      flash[:alert] = 'Something went Wrong'
      render :new
    end
  end

private
  def event_params
    params.require(:event).permit(:name, :start, :end, :contact, :location)
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/index.html.erb
<h1> Events </h1>
<%= link_to 'Create Event', new_event_path, class: 'btn btn-primary' %>
<% @events.each do |event| %>
<br/><br/>
<div class="card" style="width: 20rem;">
  <img class="card-img-top" src="http://placekitten.com/g/318/180" alt="Card image cap">
  <div class="card-block">
    <h4 class="card-title"><%= event.name %></h4>
    <p class="card-text"><%= event.start %> - <%= event.end %> at <%= event.location %></p>
    <%= link_to "View Event", event_path(event), class: 'btn btn-primary' %>
  </div>
</div>
<% end %>

app/views/events/new.html.erb
<section class='container'>
<%= form_for @event do |f| %>
<div class="form-group row">
     <%= f.label :name, class: 'col-sm-2 col-form-label'%>
     <div class="col-sm-10">
       <%= f.text_field :name , class: "form-control", placeholder: 'Festival 1'%>
     </div>
</div>
<div class="form-group row">
     <%= f.label :start, class: 'col-sm-2 col-form-label'%>
     <div class="col-sm-10">
       <%= f.date_field :start , class: "form-control", placeholder: 'Start Date'%>
     </div>
</div>
<div class="form-group row">
     <%= f.label :end, class: 'col-sm-2 col-form-label'%>
     <div class="col-sm-10">
       <%= f.date_field :end , class: "form-control", placeholder: 'End Start'%>
     </div>
</div>
<div class="form-group row">
     <%= f.label :contact, class: 'col-sm-2 col-form-label'%>
     <div class="col-sm-10">
       <%= f.text_field :contact , class: "form-control", placeholder: 'Contact'%>
     </div>
</div>
<div class="form-group row">
     <%= f.label :location, class: 'col-sm-2 col-form-label'%>
     <div class="col-sm-10">
       <%= f.text_field :location , class: "form-control", placeholder: 'Location'%>
     </div>
</div>

 <div class="form-group row">
   <div class="offset-sm-2 col-sm-10">
     <%= f.submit "Create Event", class:'btn btn-primary'%>
   </div>
</div>
<% end %>
</div>

app/views/events/show.html.erb
<h1><%= @event.name %> </h1>





<div class='card'>
  <div class="card-block">
    <%= link_to 'Attend User', new_event_reserf_path(@event), class: 'btn btn-primary' %>
    <%= link_to 'User Sign-In', edit_event_reserf_path(@event), class: 'btn btn-primary' %>
    <br/><br/>
    <div class='row'>
    <div class='col'>
      <span class=''>People Reserved:</span> <%= @reserve.length %>
    </div>
    <div class='col'>
      <span class=''>People signed-In:</span> <%= @reserve.where(ticket: true).length %>

    </div>
    </div>
  </div>
</div>



<h1>Booths</h1>
<table class="table">
  <thead>
    <tr>
      <th>Event</th>
      <th>Name</th>
      <th>Start</th>
      <th>End</th>
      <th>Sponser</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @booths.each do |booth| %>
      <tr>
        <td><%= booth.event.name %></td>
        <td><%= booth.name %></td>
        <td><%= booth.start %></td>
        <td><%= booth.end %></td>
        <td><%= booth.sponser %></td>
        <td><%= link_to 'Show', event_booth_path([@event, booth]) %></td>
        <td><%= link_to 'Edit', edit_event_booth_path([@event, booth]) %></td>
        <td><%= link_to 'Destroy', event_booth_path(@event, booth), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Booth', new_event_booth_path(@event) %>